### ISSUE TITLE
GOsa warns about NFS issues if a user is member of more than 16 POSIX groups

### ISSUE THREAD

**Issue by sunweaver** [gosa-project/gosa-core#1]
If I have a user that is member of more than 16 POSIX groups, GOsa produces the below error message (in German):

"""
Gruppenmitgliedschaft (=group membership)
(Warnung: mehr als 16 Gruppen werden von NFS nicht unterstützt!) 
(=Warning: not more than 16 groups supported by NFS)
"""

The proble should not exist anymore on modern Linuxes, see below link:
http://www.xkyle.com/solving-the-nfs-16-group-limit-problem/

I suggest dropping this warning message entirely. Feedback? Comments?

**Comment by cajus** [comment]
I'm fine with dropping it. We should reference "rpc.mountd –manage-gids" somewhere in the docs, though.
