### ISSUE TITLE
Gosa broken in Debian stretch

### ISSUE THREAD

**Issue by martux69** [gosa-project/gosa-core#10]
Hi,

after upgrading to Debian Stretch my Gosa installation is broken. By accessing the URL I get only plain html (smarty) code.
"gosa 2.7.4+reloaded2-13" and  "smarty3 3.1.31+20161214.1.c7d42e4+selfpack1-2" from debian main repo is installed.
Are there some hints how to solve it ?
Best regards
Martin

**Comment by master-caster** [comment]
Hello,

try removing /var/spool/gosa/*
it contains all the precompiled templates

- Do you upgraded from php5 to php7?
In this case there might be missing dependencies that may cause such problems.

- Did you executed update-gosa from you gosa root path?

**Comment by martux69** [comment]
Hello,

I removed all content from /var/spool/gosa/ and also did an update-gosa.
The trigger was the php update: With php5 all works fine, but with php7 not.
A few days ago there was an update for smarty from the debian repository. After installing it all works fine again.

You can close this issue.

Thank your for answering.

Best regards

-----Ursprüngliche Nachricht-----

**Comment by master-caster** [comment]
Hello,

good to hear it's working again.
