### ISSUE TITLE
Remove mcrypt dependencies

### ISSUE THREAD

**Issue by master-caster** [gosa-project/gosa-core#12]
Based on the bugreport

[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=889811](url)

we need to remove mcrypt dependencies to get GOsa² working on PHP 7.2
Mcrypt is used in Gosa² to generate hashes.

**Comment by master-caster** [comment]
It seems that it is not possible to make the generated mcrypt hashes compatible with 
the openssl cipher aes-256-ecb.

aes-256-ecb may produce compatible values if we used to pad our values like this:
[https://stackoverflow.com/questions/43482840/php-convert-mcrypt-encrypt-to-openssl-encrypt-soap-header?rq=1](url)

Modifying the current mcrypt implementation is not an option.

I used to get simliar hashes 
<pre>
base64 encoded hashes:
string(60) "openssl encode: dNcaFhGCcFGyNAtsjghLcCEuySgccx4XIxQjAM0THz4="
string(39) "Mcrypt encode: dNcaFhGCcFGyNAtsjghLcA=="
</pre>
after i manually padded the value that is about to be encrypted with openssl by a multiple of the block size.
Mcrypt uses this behaviour by default so I thought I could give it a try
but the openssl hashes are much longer.

It looks like the hash is filled by a default behaviour of the used openssl cipher since the first
bytes are literally the same.

BUT messing around with hashes is not an option.

For the time being it looks like existing GOsa² installations need to migrate.

**Comment by nacc** [comment]
Hi,

We are moving to PHP7.2 exclusively in Ubuntu Bionic (18.04). I'm not entirely sure I can tell from the last line above if this will be resolved any time soon, or if we should remove gosa from Ubuntu?

-Nish

**Comment by master-caster** [comment]
Hello,

getting a working fix and using openssl instead of mcrypt isn't the real Challenge here.
We need to implement an update mechanism that rehashes the passwords from
your gosa.conf. 

But at the time you update your installation from php 7.x to php 7.2 we can't use
mcrypt to decrypt your passwords.

I think the update to be compatible with php 7.2 will be there soon.
I can't say anything about an exact release date but that shouldn't take to long.

The migration process is something i need to investigate further to be clear if
there is an affordable and elegant way.

**Comment by master-caster** [comment]
Okay it's easy enough to do this.... xD

**Comment by master-caster** [comment]
New installations will use openssl by default now.

If you have to migrate from an old gosa installation there is a migration script now available.
The script **gosa-mcrypt-to-openssl-passwords** has to be executed exactly once and
only if you used encrypted passwords in gosa.conf before.

All other mcrypt dependencies were simply removed.
