### ISSUE TITLE
Couldn't not bind to ldap due to wrong password decryption

### ISSUE THREAD

**Issue by master-caster** [gosa-project/gosa-core#13]
As you can see here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892546

There is a bug that should only affect gosa instances migrating from unencrypted gosa.conf
to an encrypted one.

**Comment by master-caster** [comment]
To resolve this problem you need to re- encrypt your gosa.conf.
Remove gosa.secret and use plain password in gosa.conf.

Then run the encryption script again. If your web-server configuration is 
correct you should be able to use encrypted passwords.

**Comment by SkolePower** [comment]
Hi, I have done:

**1. cp /etc/gosa/gosa.conf.orig /etc/gosa/gosa.conf**
**2. sh -c “cat /dev/null > /etc/gosa/gosa.secrets”** - and also try **rm  /etc/gosa/gosa.secrets** -
**3. create /bin/gosa-encrypt-passwords** -as the correct encryption method said above-
**4. service apache2 reload**

but i get the same problem: "Error while connecting to LDAP: Could not bind to 
cn=gosa-admin,ou=ldap-access,dc=skole,dc=skolelinux,dc=no 
(unauthenticated bind (DN with no password) disallowed, while operating 
on using LDAP server ldap://ldap.intern)"

something is still not working, what is it??

The problem should be in:

a. How i do the step: **use plan passsord in gosa.conf**?
b. Must **/bin/gosa-encrypt-passwords** have special permissions?
c. How i set **web-server configuration**?

Thanks.

**Comment by master-caster** [comment]
Hello,


to solve your problem make sure your credentials
are correct and that gosa is able to reach your LDAP.

Maybe try to use a gosa.conf with plain passwords first.
If that works you need to run the following steps to
encrypt your passwords.

1. make sure you have the latest version of the encryption script:
https://github.com/gosa-project/gosa-core/commit/a389ec1e5ab8815afb9314555094fc11dce4caf6

2. make sure there is no "gosa.secrets" - file in your /etc/gosa

3. run the encryption script as root: "gosa-encrypt-passwords"

At this point you should have a gosa.secrets in /etc/gosa/.
Its content should look like this:

> RequestHeader set GOSAKEY YOUR_SECRET

The secret is auto-generated.

In most cases you don't need to care about permissions but your
Web-Server has to be able to read the file since it will be included.
So the script will set gosa.secrets to read only just for root.

Check that gosa.conf contains password hashes now.

4. Configure you Web-Server. Example from the script:

> Alias /gosa /usr/share/gosa/html

> <Location /gosa>
>  php_admin_flag engine on
>  php_admin_value open_basedir
"/etc/gosa/:/usr/share/gosa/:/var/cache/gosa/:/var/spool/gosa/"
>  php_admin_flag register_globals off
>  php_admin_flag allow_call_time_pass_reference off
>  php_admin_flag expose_php off
>  php_admin_flag zend.ze1_compatibility_mode off
>  include /etc/gosa/gosa.secrets
> </Location>

This example is for an older version of the apache Web-Server.
The most important part is

> include /etc/gosa/gosa.secrets

This directive will include your gosa.secrets.
This file is used to set an additional "RequestHeader" containing
your secret only visible for backend processing.

This header must be available to the backend. Otherwise
encrypted passwords don't work.

If you don't use apache check the documentation of your web-server
how to set additional request header.

If you do use apache make sure your gosa configuration is used.
If you have "<IfModule>" conditions in your config it may happen
that the configuration isn't use. The

> Alias /gosa /usr/share/gosa/html

itself will enable apache to access gosa. Since there is an
index.html you will see the login page. But that doesn't mean
that the "<Location ..>" is used.

After all these steps you should be able to use encrypted
passwords.



Best regards
