### ISSUE TITLE
What is the current status of this project?

### ISSUE THREAD

**Issue by wolfff** [gosa-project/gosa-core#32]
This project seems to be orphaned - especially as the host for the linked wiki ( https://oss.gonicus.de/ ) does no longer exist and the former project homepage ( www.gosa-project.org ) resolves into forbidden. 

So please send us a ping if this is actively maintained.

**Comment by kocio-pl** [comment]
I have contacted wit Cajus directly and I got the response that the project is in maintenance mode now with no future development plans. I hope someone will make this clear in the README, so it would be clear for all in the future, but that wouldn't change the state of things.

**Comment by master-caster** [comment]
There is a note attached to thre README.md that describe the current project status.
As already mentioned, for now, it is not planed to create any major changes. 

I'm closing this issue since I think it is "fixed". If you don't think so feel free to open it again
or to raise a new issue
