### ISSUE TITLE
messages.po screwed?

### ISSUE THREAD

**Issue by infoomatic** [gosa-project/gosa-core#39]
seems like the messages.po in master are screwed, e.g. in locale/core/nl/LC_MESSAGES ... they contain metadata from development utils like HEAD

**Comment by dzatoah** [comment]
Even better commit 01260fc188 fucked up the entire code base somehow.
It's not just the .po files.

@Juinness

**Comment by Juinness** [comment]
Sorry for the late feedback. I have just undone the erroneous merge conflicts and thus the master branch should be clean again.
