### ISSUE TITLE
GOsa v2.8: Leave more spacing for timezone dropdown menus

### ISSUE THREAD

**Issue by dzatoah** [gosa-project/gosa-core#48]
As you can see the text is almost not readable. (timezone at the bottom is selected)
![grafik](https://user-images.githubusercontent.com/16420080/207853965-5bc4bd0e-a3c5-4e57-861d-673b716d72a1.png)

 @Juinness

**Comment by dzatoah** [comment]
Oh and a little personal update: I've got my test setup working now. Including `gosa-plugin-sudo`.  @Juinness

**Comment by Juinness** [comment]
I have adjust all input items. @dzatoah good to hear that u have fixed ur setup.
