### ISSUE TITLE
GOsa v2.8: Javascript variable referenced in PHP code?

### ISSUE THREAD

**Issue by dzatoah** [gosa-project/gosa-core#49]
Please see this code line:

https://github.com/gosa-project/gosa-core/blob/f9076ea8951271da3a0e81b97c2db53c35a20f93/plugins/generic/references/class_aclResolver.inc#L412

I think this is a javascript/css variable or something? Neither my IDE nor PHP can figure out where this comes from.
While trying to edit a user I encountered the following error message:

```php
Fatal error: Uncaught Error: Undefined constant "screen" in /usr/share/gosa/plugins/generic/references/class_aclResolver.inc:412
Stack trace: #0 /usr/share/gosa/plugins/generic/references/class_reference.inc(160): aclResolver->getReadableACL()
#1 /usr/share/gosa/include/class_tabs.inc(171): reference->execute()
#2 /usr/share/gosa/include/class_management.inc(210): tabs->execute()
#3 /usr/share/gosa/plugins/admin/users/main.inc(44): management->execute()
#4 /usr/share/gosa/html/main.php(417): require('...')
#5 {main} thrown in /usr/share/gosa/plugins/generic/references/class_aclResolver.inc on line 412
```

@Juinness

**Comment by Juinness** [comment]
@dzatoah I have investigated this further, probably this has been committed incorrectly from older changes. But I have now written the screen width into the §_SESSION when starting GOsa.
