### ISSUE TITLE
GOsa v2.8 (develop-branch): Commit 5ad1dd26 breaks dashboard tiles.

### ISSUE THREAD

**Issue by dzatoah** [gosa-project/gosa-core#55]
Bei einem Klick auf eine Kachel (z.B. eine Addon-Kachel) auf der Startseite wurde man nur wieder zur Startseite weitergeleitet.
Wenn man nun auf Einstellungen an der seitlichen Navbar drückt, dann kommt man über Umwege trotzdem ans Ziel. (Workaround)

When you click on a tile (e.g. an addon tile) on the start page, you were only redirected to the start page.
If you now press settings on the side navbar, you will still reach your goal via detours. (workaround)

**Comment by Juinness** [comment]
Wurde mit #56 gefixt und ist auf dem Pre-Release gemerged
