### ISSUE TITLE
PHP 7: old style class constructors everywhere

### ISSUE THREAD

**Issue by sunweaver** [gosa-project/gosa-core#6]
GOsa classes use PHP old-style constructor methods (contructor method has the same name as the class name).

This is deprecated in PHP 7.x and should be migrated to using methods of the name __construct().

See:
http://php.net/manual/en/migration70.deprecated.php

**Comment by sunweaver** [comment]
@cajus: Are you sure that faec5d82ca016d1239e87efcef3fe441015126fe covers all the constructors being around in GOsa?

With this simple one liner run over a dir with gosa-core and all available plugins (in separate folders), I see many more constructor methods of deprecated style:

```
grep -ri '^class ' * | sed -r 's/.*class\ (.*)($|\ \{|\sextends.*)/\1/g' | grep -v "{" | grep -v "}" | while read class; do grep -ri "function $class"; done
```

**Comment by cajus** [comment]
```
#!/bin/bash

classes=$(grep -r ^class * | sed 's/: *class *\([^ {]*\).*$/:\1/')

for line in $classes; do
  split=(${line//:/ })
  class=${split[1]}

  sed -i "s/function ${class} *(/function __construct(/" ${split[0]}
done
```

**Comment by sunweaver** [comment]
Uploaded to Debian as gosa 2.7.4+reloaded2-11:

http://anonscm.debian.org/cgit/debian-edu/pkg-team/gosa.git/commit/?id=8667aee84a19a5d912370fb6e2ab20fb9a4a1628

**Comment by sunweaver** [comment]
It seems you have committed the required changes to all plugins, as well. Please close this bug, when/if done. Thanks!

**Comment by sunweaver** [comment]
Improved script version...

```
#!/bin/bash

classes=$(grep -r -E "^class [_a-zA-Z0-9]" * | sed -r -e 's/(.*):class\ ([^\ {]+).*$/\2:\1/' | sort | uniq)

for line in $classes; do
  split=(${line//:/ })
  class=${split[0]}

  if [ "${last_class}" = "${class}" ]; then
    continue
  fi
  last_class="${class}"
  echo $class   ----   ${split[1]}

  sed -i "s/function ${class} *(/function __construct(/" ${split[1]}

  find * -type f | egrep "\.php|\.inc" | while read file; do
    if [ "${class}" != "xml" ]; then
    sed -r -e "s/${class}::${class}/${class}::__construct/" -i "$file"
    fi
  done

done
```

**Comment by sunweaver** [comment]
@cajus: Forgot to mention, the new script applies more changes on the code tree, esp. the calling of constructors gets fixed (plugin::plugin() -> plugin::__construct().

Thus, you/me needs to run the script over all gosa components and commit the additional changes.

@cajus: can you do that? Or shall I put that on my list?

**Comment by master-caster** [comment]
This additional fix is now applied.

Since this change is needed for most repositories you have to look for the
changes in each repository on your own.
